# environment to run brainbot
FROM alpine:3.19

WORKDIR /app

# download necessary tools first
RUN apk update && apk add --no-cache build-base cmake unzip openssl-dev spdlog-dev zlib-dev

# download and build hiredis, needed by redis-plus-plus
ARG hiredis_v=1.2.0
ARG hiredis_t=v$hiredis_v.zip
ARG hiredis=hiredis-$hiredis_v

RUN wget https://github.com/redis/hiredis/archive/refs/tags/$hiredis_t \
    && unzip $hiredis_t \
    && cd $hiredis \
    && make \
    && make install \
    && cd .. \
    && rm -rf $hiredis $hiredis_t

# download and build redis-plus-plus
ARG redispp_v=1.3.12
ARG redispp_t=$redispp_v.zip
ARG redispp=redis-plus-plus-$redispp_v

RUN wget https://github.com/sewenew/redis-plus-plus/archive/refs/tags/$redispp_t \
    && unzip $redispp_t \
    && cd $redispp \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && make install \
    && cd ../.. \
    && rm -rf $redispp $redispp_t

# download and build dpp
ARG DPP_v=10.0.29
ARG DPP_t=DPP-$DPP_v.zip
ARG DPP=DPP-$DPP_v

RUN wget https://github.com/brainboxdotcc/DPP/releases/download/v10.0.29/$DPP_t \
    && unzip $DPP_t \
    && cd $DPP \
    && mkdir build \
    && cmake -B ./build \
    && cmake --build ./build -j4\
    && cd build \
    && make install \
    && cd ../.. \
    && rm -rf $DPP $DPP_t

ENTRYPOINT [ "sh" ]