# container for running the bot
FROM alpine:3.19

RUN apk add cmake make g++ sudo openssl-dev spdlog-dev zlib-dev

# create user
RUN adduser -D runner
RUN echo "runner ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/packager

# copy the lib apks
COPY ./.abuild/packages/ /.abuild/libs

# copy any rsa key for signing the apk later, will throw error if no rsa key found.
COPY ./.abuild/*rsa* /.abuild/

# copy the pub key to /etc/apk/keys
RUN find /.abuild -type f -name "*.pub" -exec sudo cp {} /etc/apk/keys \;

# install libs
RUN sh -c "find /.abuild/libs -type f -name "*.apk" -exec apk add {} \;"

USER runner

ENTRYPOINT [ "sh", "-c" ]